### PR TITLE
Migration to CKAN 2.3

### PR DESCRIPTION
**Pull request by deniszgonjanin**
This PR addresses code changes for migrating the catalogue to CKAN 2.3. In addition, a few other things need to happen for a successful migration:

##### Setup
- Run database migration for 2.3. This can be done with `paster db upgrade’
- `pdf_preview` extension no longer exists. Need to install https://github.com/ckan/ckanext-pdfview.git
- CKAN 2.3. uses the new ResourceView feature instead of resource previews. For geographic views, this extension needs to be installed: https://github.com/pduchesne/ckanext-geoview
- There is a new schema version for CKAN 2.3. This can be retrieved from the CKAN source here: https://github.com/ckan/ckan/blob/ckan-2.3/ckan/config/solr/schema.xml.
- Because of the new schema, clean the existing index, restart SOLR, and reindex everything.

##### Configuration options:
- `ckanext.geoview.ol_viewer.formats = wms kml geojson`
- change `ckan.plugins = … text_preview pdf_preview recline_preview` to `ckan.plugins = … text_view pdf_view recline_view`
- `ckan.views.default_views = text_view recline_view geo_view pdf_view`

##### Creating the new Resource Views:
The new views for geospatial, tabular, pdf, etc... will not appear automatically like the old resource previews. They need to be created via a paster command:
`paster --plugin=ckanext-bcgov edc_command create-views`

### CODE REVIEW

**Comment by wardi** [comment]
@ll911 Please take a look at @deniszgonjanin 's steps above for running on the delivery environment

**Comment by ll911** [comment]
@wardi @deniszgonjanin is current ckanext-bcgov master work with ckan2.3? I will take a full backup and upgrade edcdlv ckan core from 2.2.1 to 2.3 with pip upgrade.

**Comment by deniszgonjanin** [comment]
@ll911 yes, this merged pull request brings code changes needed for 2.3 into ckanext-bcgov master.

**Comment by ll911** [comment]
@wardi  @deniszgonjanin Great, I’m working on backup the current instance. Can you update the dlv.ini for delivery and schema.xml for solr in svn for new release?

**Comment by ll911** [comment]
@wardi @deniszgonjanin ckan pip upgrade log as 

pip install --upgrade ckan==2.3
Downloading/unpacking ckan==2.3
  Downloading ckan-2.3.tar.gz (6.9MB): 6.9MB downloaded
  Running setup.py (path:/apps/ckan/dlv/build/ckan/setup.py) egg_info for package ckan

    warning: no files found matching '*' under directory 'ckanext/*/i18n'
    no previously-included directories found matching '.git'
    warning: no files found matching 'CHANGELOG.txt'
    warning: no files found matching '*' under directory 'ckan_deb'
Installing collected packages: ckan
  Found existing installation: ckan 2.2.1
    Uninstalling ckan:
      Successfully uninstalled ckan
  Running setup.py install for ckan

    warning: no files found matching '*' under directory 'ckanext/*/i18n'
    no previously-included directories found matching '.git'
    warning: no files found matching 'CHANGELOG.txt'
    warning: no files found matching '*' under directory 'ckan_deb'
    Skipping installation of /apps/ckan/dlv/lib/python2.7/site-packages/ckanext/__init__.py (namespace package)
    Skipping installation of /apps/ckan/dlv/lib/python2.7/site-packages/ckanext/stats/__init__.py (namespace package)
    Installing /apps/ckan/dlv/lib/python2.7/site-packages/ckan-2.3-py2.7-nspkg.pth
    Installing ckan-admin script to /apps/ckan/dlv/bin
Successfully installed ckan
Cleaning up...

**Comment by ll911** [comment]
@deniszgonjanin @wardi for the resource visualization, can the manual effort for view creation process  back to automatic or integrate with celeraryd?

**Comment by deniszgonjanin** [comment]
@ll911 the manual command for creating the views should only need to be ran once, in order to migrate the old CKAN 2.2 previews into views. Going forward, any newly created resource will have it's views automatically created based on the `ckan.views.default_views` config parameter.

If you find that this isn't the case, let me know

**Comment by ll911** [comment]
@deniszgonjanin then we have an issue that new created resource can not be viewed. e.g http://cad.data.gov.bc.ca/dataset/testing-geographic/resource/92479e9f-6e2b-4624-afec-45ea076a2ae1

**Comment by deniszgonjanin** [comment]
It looks like there are no views created for that resource, which suggests that the 'paster edc_command create_views' did not finish running properly, or perhaps something is misconfigured in the .ini. I'll take a closer look

**Comment by ll911** [comment]
@deniszgonjanin thx, the resource were added after 'paster edc_command create_views'

**Comment by deniszgonjanin** [comment]
@ll911 thanks, that's very helpful. That suggests there's a configuration problem somewhere, as those views should be created automatically

**Comment by ll911** [comment]
@deniszgonjanin can you check dlv.ini file? let me know if you cant access it.

**Comment by deniszgonjanin** [comment]
Yes - the `dlv.ini` seems fine at first glace. I'm going to try using the same settings locally to see if we can reproduce the error

**Comment by deniszgonjanin** [comment]
the resource creation is fixed by 7bce9221cfb880ea2e0b09d3538919663afe9680 

The problem was that the bcgov extension is overriding a lot of core CKAN controller and action API functionality, so as CKAN changes, we have to manually port changes from CKAN into the extension code that overrides it.

The commit above is just a stopgap then, and in the long run we must refactor the code so it is using the plugin interfaces to create new functionality instead of overriding core CKAN methods.

All to say is, other regression errors like this one may appear one until that effort is complete.

**Pull request merged**
