### PR TITLE
block user registration form

### PR DESCRIPTION
**Pull request by perceptron-XYZ**
The problem:
With edc-idir plugin enabled, users cannot have access to /user/register on the UI, but they can write scripts to POST form info to /user/register. This is not taken care of by IAuthFunctions.

Desired situation and solution:
If a user is logged in, access to /user/register will ask him or her to log out first, just like ckan
If an unlogged in user tries to access /user/register, use the behaviour from edc-idir.
SOLUTION is the combine the behaviour of those two packages, and make our own customized register method.

### CODE REVIEW

**Comment by ll911** [comment]
@perceptron-XYZ can you resolve the conflicts first?

**Comment by gjlawran** [comment]
@wardi Are you able to resolve conflicts on this merge?

**Comment by wardi** [comment]
sure I'll take a look tomorrow

**Comment by wardi** [comment]
replaced by #40

**Pull request closed without merging**
